 CREATE TABLE ITEMS
   (	
	ITEMNO INT(50), 
	ITEMNAME VARCHAR(50), 
	ITEMPRICE VARCHAR(50), 
	ITEMTYPE VARCHAR(50), 
	ITEMUSE VARCHAR(50), 
	ITEMIMG VARCHAR(50), 
	ITEMDESC VARCHAR(2000), 
	ITEMDATE DATE, 
	ITEMSTOCK INT(50),
	PRIMARY KEY (ITEMNO)
   )
   
   CREATE TABLE MYCART 
   (	CARTNAME VARCHAR(50), 
	ITEMNO INT(50), 
	ITEMNAME VARCHAR(50), 
	PRICE INT(50 ), 
	QUANTITY INT(50) DEFAULT 1, 
	CARTNO INT(50),
	PRIMARY KEY (CARTNO)
   )
	
	
	CREATE TABLE REVIEW 
   (	RID VARCHAR(50), 
	REVIEWNO INT(50), 
	STAR VARCHAR(50), 
	CONTENT VARCHAR(2000), 
	ITEMNO INT(50), 
	ITEMNAME VARCHAR(50), 
	REGDATE DATE,
	PRIMARY KEY(REVIEWNO)
   ) 
   
   CREATE TABLE ORDERLIST 
   (	ORDERLISTNAME VARCHAR(50), 
	ORDERNO VARCHAR(50), 
	ORDERDATE DATE, 
	ITEMNAME VARCHAR(50), 
	STATUS VARCHAR(50), 
	ADDRESS VARCHAR(50), 
	ITEMNO INT(50), 
	QUANTITY INT(50), 
	PRICE INT(50), 
	TOTAL INT(50),
	PRIMARY KEY (ORDERNO)
   )